Repository foundeo/cfdocs, pull requests merged in 2022-10, with the labels that each got.

#1559 Fix typo in onRequest function in Application.cfc
  data/en/onrequest.json
Labels: hacktoberfest

#1537 Fix word case: `lucee` -> `Lucee`
  data/en/booleanformat.json
  data/en/getcanonicalpath.json
  data/en/getfunctionkeywords.json
  data/en/pagepoolclear.json
  data/en/pagepoollist.json
  data/en/trace.json
  guides/en/server-scope.md
  tests/tests/TestExamples.cfc
Labels: hacktoberfest

#1539 Added member function syntax to dateFormat()
  data/en/dateformat.json
Labels: hacktoberfest

#1541 Add member function syntax to month()
  data/en/month.json
Labels: hacktoberfest

#1542 Add member function syntax for day()
  data/en/day.json
Labels: hacktoberfest

#1544 Update listqualify.json
  data/en/listqualify.json
Labels: hacktoberfest

#1548 Update README.md
  README.md
Labels: hacktoberfest

#1558 Update cfmodule.json
  data/en/cfmodule.json
Labels: hacktoberfest

#1556 Update query-functions.json
  data/en/query-functions.json
Labels: hacktoberfest

#1502 Image captcha
  data/en/functions.json
  data/en/imagecaptcha.json
  data/en/index.json
  guides/en/lucee-only.md
Labels: hacktoberfest, change-requested, hacktoberfest-accepted

#1562 Fix word case: `xml` -> `XML`
  data/en/cfxml.json
  data/en/htmlparse.json
  data/en/isarray.json
  data/en/isxmldoc.json
  data/en/isxmlelem.json
  data/en/xmlvalidate.json
Labels: hacktoberfest, hacktoberfest-accepted

#1563 Fix word case and grammar
  assets/code-editor.js
  data/en/canonicalize.json
  data/en/cfform.json
  data/en/cfformitem.json
  data/en/cfhtmlbody.json
  data/en/cfmap.json
  data/en/cfmapitem.json
  data/en/cfspreadsheet.json
  data/en/esapidecode.json
  lib/Processor.cfc
Labels: hacktoberfest, hacktoberfest-accepted
